services:
  - type: web
    name: gallery
    buildCommand: npm install && npm audit fix --force
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000